### ISSUE TITLE
State diff data not stored for Genesis Block

### ISSUE THREAD

**Issue by jbcaron** [KasarLabs/deoxys-fork#107]
# Bug Report

**Madara version:** a856f04

**Current behavior:**

Genesis block does not store state diff (contracts and class hash equivalence). This bug impacts the following rpc methods:

- `getTransactionByHash`
- `getTransactionReceipt`
- `getClassHashAt`
- `getClassAt`

> :bulb: `ContracClass` storage is handled separately and is therefore not impacted by this issue.

**Expected behavior:**

Rpc calls to a Deoxys node should be able to retrieve state diff data on block 0.

**Steps to reproduce:**

Make a `starknet_getTransactionByHash`, `starknet_getTransactionReceipt`, `starknet_getClassHashAt` or `starknet_getClassAt` rpc call on a target contract defined at block 0.

**Related code:**

- [`fetch_genesis_block`](https://github.com/KasarLabs/deoxys/blob/a856f047757a20431c29df36e4a86512ad63f8ce/crates/client/deoxys/src/l2.rs#L212)
- [`run_node`](https://github.com/KasarLabs/deoxys/blob/a856f047757a20431c29df36e4a86512ad63f8ce/crates/node/src/commands/run.rs#L223)

**Other information:**

A good solution to this issue would be to convert the genesis block state update to a [`StateUpdateWrapper`](https://github.com/KasarLabs/deoxys/blob/a856f047757a20431c29df36e4a86512ad63f8ce/crates/primitives/block/src/state_update.rs#L11) inside of [`new_full`](https://github.com/KasarLabs/deoxys/blob/a856f047757a20431c29df36e4a86512ad63f8ce/crates/node/src/service.rs#L272) and send it to the digest using the existing [state update channel](https://github.com/KasarLabs/deoxys/blob/a856f047757a20431c29df36e4a86512ad63f8ce/crates/node/src/service.rs#L451). Storing in db would then be automatically handled inside of [`on_initialize`](https://github.com/KasarLabs/deoxys/blob/a856f047757a20431c29df36e4a86512ad63f8ce/crates/pallets/starknet/src/lib.rs#L220)

**Comment by Trantorian1** [comment]
See pull request #122 for a fix
