### ISSUE TITLE
dev:  Define consensus on logging practices within the codebase

### ISSUE THREAD

**Issue by jbcaron** [KasarLabs/deoxys-fork#140]
## Overview
We've observed a variety of logging practices across our codebase, including the use of `log::info!`, `log::warn!`, `log::debug!`, and `log::error!`, as well as custom logging macros within crates like `pallets::starknet::lib`. This inconsistency can lead to challenges in maintaining and debugging the code effectively. The aim of this issue is to establish a clear and consistent logging strategy that all contributors can follow.

## Current Situation
Currently, contributors use a mix of logging levels and macros based on personal preference or situational judgement.
Additionally, we have custom macros such as:

```rust
#[macro_export]
macro_rules! log {
    ($level:tt, $pattern:expr $(, $values:expr)* $(,)?) => {
        log::$level!(
            target: $crate::LOG_TARGET,
            concat!("[{:?}] 🐺 ", $pattern), <frame_system::Pallet<T>>::block_number() $(, $values)*
        )
    };
}
```
This macro enriches log messages with contextual information like block numbers,

## Proposal for Consensus

To standardize our logging practices, I propose the following guidelines:

1. **Use log::debug! sparingly:** Reserve for detailed information valuable during development or debugging, not intended for production environments.
2. **Adopt log::info! for operational messages:** Information that could be useful to have in logs for production environments, including start-up configurations or significant state changes.
3. **Apply log::warn! for non-critical issues:** Situations that are unexpected or undesirable, yet do not halt program execution, should be logged at this level.
4. **Reserve log::error! for critical errors:** Use this level for logging errors that may cause a halt in program execution or significantly impact performance.
5. **Custom Logging Macros:** For modules that require additional context in logs, continue using or developing custom macros that adhere to the above log level guidelines. Ensure these macros are well-documented and their usage is justified.

## Request for Comments (RFC)

I encourage all team members to provide their input on these proposed guidelines. Are there any additional considerations we should take into account? Do certain modules or components require exceptions to these rules?

## Conclusion

Establishing a consensus on our logging practices will help us maintain a clean, informative, and useful log system across our entire codebase. This will not only aid in debugging and development but also ensure that our logs are valuable resources for understanding system behavior and diagnosing issues.

**Comment by noamoulin** [comment]
## Redirecting logs: TUI dashboard case

In order to retrieve logs from the optional dashboard integrated into Deoxys that I'm developing, it must be possible to redirect them, for example, into an MPSC channel by defining a  custom global writer for all Deoxys logs.
