### ISSUE TITLE
feat/starknet_chainId

### ISSUE THREAD

**Issue by antiyro** [KasarLabs/deoxys-fork#41]
### Issue: Implement `starknet_chainId` RPC Call

**Description:**  
The `starknet_chainId` RPC call has been implemented but requires further testing and verification against the entire state. This RPC call returns the currently configured StarkNet chain id.

**Parameters:**  
None.

**Expected Result:**  
The chain id this node is connected to.

**Testing:**  
Initial testings can be found [here](https://github.com/KasarLabs/deoxys/tree/deoxys/dev/tests/tests/tests-deoxys/rpc). However, these should not be considered complete and improvements are welcome.

**Resources:**  
- [Alchemy RPC API Endpoint Documentation](https://docs.alchemy.com/reference/starknet-api-endpoints)
- [Starknet API OpenRPC Spec](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json)

**Comments:**  
Please comment below for coordination.

**Comment by jbcaron** [comment]
can I take this one

**Comment by jbcaron** [comment]
## tests:

- [X] mainnet 
- [ ]  testnet

**Comment by antiyro** [comment]
This issue could go a bit further to bring support to a dynamic chain id based on cli on the whole codebase. @nils-mathieu initiated the --network handling now the code base should be updated accordingly to relay it until the rpc client side.

Also please support integration network: https://github.com/KasarLabs/deoxys/blob/main/crates/node/src/commands/run.rs#L91
