### ISSUE TITLE
feat/starknet_syncing

### ISSUE THREAD

**Issue by antiyro** [KasarLabs/deoxys-fork#43]
### Issue: Implement `starknet_syncing` RPC Call

**Description:**  
The `starknet_syncing` RPC call has been implemented but requires further testing and verification against the entire state. This RPC call returns an object about the sync status, or `false` if the node is not syncing.

**Parameters:**  
None.

**Expected Result:**  
The state of the synchronization, or `false` if the node is not synchronizing. The status can either be `FALSE` or a `Sync status` object.

**Testing:**  
Initial testings can be found [here](https://github.com/KasarLabs/deoxys/tree/deoxys/dev/tests/tests/tests-deoxys/rpc). However, these should not be considered complete and improvements are welcome.

**Resources:**  
- [Alchemy RPC API Endpoint Documentation](https://docs.alchemy.com/reference/starknet-api-endpoints)
- [Starknet API OpenRPC Spec](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json)

**Comments:**  
Please comment below for coordination.

**Comment by jbcaron** [comment]
can i take this one?

**Comment by jbcaron** [comment]
# test diff
- ```result.highest_block``` : pathfinder gives the highest block in the chain even if it is not totally synchronized, deoxys gives the highest synchronized block
