### ISSUE TITLE
feat/starknet_getNonce

### ISSUE THREAD

**Issue by antiyro** [KasarLabs/deoxys-fork#45]
### Issue: Implement `starknet_getNonce` RPC Call

**Description:**  
The `starknet_getNonce` RPC call has been implemented but requires further testing and verification against the entire state. This RPC call retrieves the nonce associated with the given address in the specified block.

**Parameters:**  
- `block_id`: The hash of the requested block, or number (height) of the requested block, or a block tag. This parameter is required.
- `contract_address`: The address of the contract whose nonce is being sought. This parameter is required.

**Expected Result:**  
The contract's nonce at the requested state.

**Potential Errors:**  
- `BLOCK_NOT_FOUND`: The specified block could not be found.
- `CONTRACT_NOT_FOUND`: The specified contract could not be found.

**Testing:**  
Initial testings can be found [here](https://github.com/KasarLabs/deoxys/tree/deoxys/dev/tests/tests/tests-deoxys/rpc). However, these should not be considered complete and improvements are welcome.

**Resources:**  
- [Alchemy RPC API Endpoint Documentation](https://docs.alchemy.com/reference/starknet-api-endpoints)
- [Starknet API OpenRPC Spec](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json)

**Comments:**  
Please comment below for coordination.

**Comment by Tbelleng** [comment]
Can i take this one ?

**Comment by antiyro** [comment]
Testing

```
curl --request POST \
     --url  https://deoxys.kasar.io/rpc \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "starknet_getNonce",
  "params": [
    {"block_number": 2000000},
    "0x200318ff43b562b16597fca1ecb0869ad2aae238c"
  ]
}
'```

Unexisting contract returns a 0x0 nonce

**Comment by Tbelleng** [comment]
*🚧 Most of those tests are tested on the first 50 000 blocs of Main net network*
*Concerning contract, tests are done on 10-15 different contracts to ensure validity*
*Version 🌐 : 0.5.1*

- Versus Madara/Deoxys :

		-fail_non_existing_block : ✅
		-fail_non_existing_contract : Waiting for deoxys Rebase
		-work_erc721_contract : 
		-work_erc20_contract :
		-work_account_contract :
		-work_account_proxy_contract :



 - Versus Pathfinder : 

		-fail_non_existing_block : ✅
		-fail_non_existing_contract : ✅
		-work_erc721_contract : ✅
		-work_erc20_contract : ✅
		-work_account_contract : ✅
		-work_account_proxy_contract : ✅


- Versus Juno : 
	
		-fail_non_existing_block : ✅ (⛔️ be careful, for block 0 Juno return a Contract not found, which is normal because of Juno implem)
		-fail_non_existing_contract : ✅
		-work_erc721_contract : ✅
		-work_erc20_contract : ✅
		-work_account_contract : ✅
		-work_account_proxy_contract : ✅
