### ISSUE TITLE
feat/networks

### ISSUE THREAD

**Issue by antiyro** [KasarLabs/deoxys-fork#49]
### Description

We need to implement support for three distinct launch modes, specifically: `integration`, `mainnet`, and `testnet`. These modes should be triggerable via the `--testnet`, `--mainnet`, and `--integration` arguments, respectively.

### Details

Using these arguments should alter the sequencer endpoint utilized to synchronize blocks:

- For `--testnet`: Testnet gateway URL - [https://alpha4.starknet.io/gateway/](https://alpha4.starknet.io/gateway/)
- For `--mainnet`: Mainnet gateway URL - [https://alpha-mainnet.starknet.io/gateway/](https://alpha-mainnet.starknet.io/gateway/)
- For `--integration`: Integration gateway URL - [https://external.integration.starknet.io/](https://external.integration.starknet.io/)

### Location

The integration should be done in the following file: [crates/node/src/cli.rs](https://github.com/KasarLabs/deoxys/blob/deoxys/prod/crates/node/src/cli.rs).

Moreover, it's necessary to tidy up what has been already implemented in [lib.rs](https://github.com/KasarLabs/deoxys/blob/deoxys/prod/crates/client/deoxys/src/lib.rs#L175) by moving it to a new `client.rs` file within the same `Deoxys` directory.

### Tasks

1. Add support for `--testnet`, `--mainnet`, and `--integration` arguments in [cli.rs](https://github.com/KasarLabs/deoxys/blob/deoxys/prod/crates/node/src/cli.rs).
2. Modify the sequencer endpoints based on the provided argument.
3. Shift the relevant code from [lib.rs](https://github.com/KasarLabs/deoxys/blob/deoxys/prod/crates/client/deoxys/src/lib.rs#L175) to a new `client.rs` file.

**Comment by nils-mathieu** [comment]
Maybe use something like `--network [main|test|integration]` instead of `--mainnet | --testnet | --integration` ? Just a dumb idea, both are basically the same.
